name: v2manager
description: Magisk插件V2ray-For-Android管理应用

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2-beta

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # url_launcher: ^6.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/